### ISSUE TITLE
Implement "Data list" components

### ISSUE THREAD

**Issue by hbjydev** [mtorromeo/vue-patternfly4#5]
Hey there! Looking at using this on a project with a friend, and we wanted to know if you have any plans to build out support for [Data Lists](https://www.patternfly.org/v4/components/data-list) at any time soon?

Thanks!

**Comment by mtorromeo** [comment]
Hi, thanks for the interest!

I am planning on porting more components in the near future and I don't mind giving a bit of priority to Data Lists, but I can't make any promise on a particular date.

Of course, I would also gladly accept contributions.

**Comment by hbjydev** [comment]
> Hi, thanks for the interest!
> 
> I am planning on porting more components in the near future and I don't mind giving a bit of priority to Data Lists, but I can't make any promise on a particular date.
> 
> Of course, I would also gladly accept contributions.

No worries! Thanks for replying regardless! I'll see what I can do in terms of contribution though, I'll have to poke around and see what I can do. Not done much with the source for the React stuff.

Thanks for the quick response :)

**Comment by hbjydev** [comment]
@mtorromeo Thanks for implementing this! :D
